version: 2.1
orbs:
  terraform: circleci/terraform@3.2.1
jobs:
  terraform-check:
    executor: terraform/default
    resource_class: small
    steps:
      - checkout
      - terraform/init:
          path: terraform
      - terraform/validate:
          path: terraform
      - terraform/fmt:
          path: terraform
    working_directory: ~/terraform
workflows:
  terraform:
    jobs:
      - terraform-check
